spring.application.name=config-server
server.port=8888
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.compatibility-verifier.enabled=false
spring.cloud.config.server.git.uri=https://github.com/velan-2484878/energy-grid-config-server.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.skip-ssl-validation=true

